### ISSUE TITLE
possible bug with pyvmomi 6, python 3.x and unicode

### ISSUE THREAD

**Issue by lsioctl** [vmware/pyvmomi#375]
Hello,

When trying to modify network configuration of a vm under a vcenter with 
french locale by defautl, a SOAP error occur only if using python 3 with latest pyvmomi.

It does not append with python 2.7.x, with the same pyvmomi version.

I'm under CentOS 6 and  tried with

- Python 3.4 from RedHat SCL : SOAP fault
- Python 3.5 from Miniconda : SOAP fault
- Python 2.7 from CentOS 6 : OK (but with no way to bypass the urrllib3 SSL warning)
- Python 2.7 from Miniconda : OK

The only difference if found between python 2.7 and 3 is, when I do 

```
print(device_change)
```

is that the network label appears in unicode python 2.7.x

```
label = u'Adaptateur r\xe9seau 1',
```

And not with python 3.x

```
label = 'Adaptateur réseau 1',
```

You'll find below the SOAP error.

Tell me If I could help, as we must not be so many with french vcenter ;).

Regards,

```
Caught vmodl fault : 
Error returned by expat parser: not well-formed (invalid token)

while parsing serialized value of type string
at line 3, column 200

while parsing property "label" of static type string

while parsing serialized DataObject of type vim.Description
at line 3, column 188

while parsing property "deviceInfo" of static type Description

while parsing serialized DataObject of type vim.vm.device.VirtualE1000
at line 3, column 141

while parsing property "device" of static type VirtualDevice

while parsing serialized DataObject of type vim.vm.device.VirtualDeviceSpec
at line 3, column 100

while parsing property "deviceChange" of static type ArrayOfVirtualDeviceConfigSpec

while parsing serialized DataObject of type vim.vm.ConfigSpec
at line 3, column 94

while parsing call information for method ReconfigVM_Task
at line 3, column 14

while parsing SOAP body
at line 3, column 0

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request for method reconfigure
on object of type vim.VirtualMachine
at line 1, column 0
```

**Comment by tianhao64** [comment]
@lsioctl Are you using 6.0.0 or the latest dev version of pyvmomi? 
Can you also post the exact call you made?

**Comment by lsioctl** [comment]
@tianhao64 

I use Pyvmomi Version: 6.0.0

The call I make is inspired from samples, I only commented what is useless
for me, and a special fonction to get object references via property collectors.

Tell me if you need more.

Regards,

```
    # This code is for changing only one Interface. For multiple Interface
    # Iterate through a loop of network names.
    device_change = []
    for device in vmobj.config.hardware.device:
        if isinstance(device, vim.vm.device.VirtualEthernetCard):
            nicspec = vim.vm.device.VirtualDeviceSpec()
            nicspec.operation = \
                vim.vm.device.VirtualDeviceSpec.Operation.edit
            nicspec.device = device
            # We do not alter this
            #nicspec.device.wakeOnLanEnabled = True

            # retreive the DVSPortgroup Managed Object Reference
            # with the network_name
            network = pyv.get_obj_ref_from_pc(si,
                        obj_type=[vim.dvs.DistributedVirtualPortgroup],
                        prop_name='name',
                        prop_value=args.network_name)
            dvs_port_connection = vim.dvs.PortConnection()
            dvs_port_connection.portgroupKey = network.key
            # Nice thing, we have de DVS uuid with this MO
            dvs_port_connection.switchUuid = \
                network.config.distributedVirtualSwitch.uuid
            nicspec.device.backing = \
                vim.vm.device.VirtualEthernetCard. \
                DistributedVirtualPortBackingInfo()
            nicspec.device.backing.port = dvs_port_connection

            # We do not alter this
            #nicspec.device.connectable = \
            #vim.vm.device.VirtualDevice.ConnectInfo()
            #nicspec.device.connectable.startConnected = True
            #nicspec.device.connectable.allowGuestControl = True
            device_change.append(nicspec)
            print(device_change)
            break

    try:
        config_spec = vim.vm.ConfigSpec(deviceChange=device_change)
        task = vmobj.ReconfigVM_Task(config_spec)
        if pyv.wait_for_task(task) == 0:
            print('Successfully changed network')

    except vmodl.MethodFault as error:
        print("Caught vmodl fault : " + error.msg)
```

**Comment by tianhao64** [comment]
@lsioctl 6.0.0 has a few python3 bugs which already been fixed in current dev version. Can you clone the latest dev version and try again?

**Comment by lsioctl** [comment]
@tianhao64 I just did clone and install the master branch, and the bug has just gone, I still have an utf8 interpretation when i use print, e.g
```
label = 'Adaptateur réseau 1',
```
but no SOAP error and everything is ok, at least with python 3.4 from RH SCL.

Is the master branch the current dev version ? Because in 

https://github.com/vmware/pyvmomi/blob/master/setup.py

I've got 
```
version='5.5.0-DEVELOPMENT'
```
Anyway I use sslContext in SmartConnect, so I'm really on a pyvmomi 6.0.0 no ?

```
si = SmartConnect(
        host=host,
        user=user,
        pwd=password,
        port=port,
        sslContext=context)
```
Regards

**Comment by tianhao64** [comment]
@lsioctl I think you were on 6.0.0 since the ssoContext is present. The version in setup.py is wrong. I will fix it in coming release.

**Comment by lsioctl** [comment]
@tianhao64 Thank you ! Waiting for next release we will use dev version or python 2.7.

**Comment by tianhao64** [comment]
I just created a new release: 6.0.0.2016.4. This issue should be fixed.
